sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services:
  - redis-server

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true

install:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
  - composer self-update

before_script:
  - composer update --prefer-dist --no-interaction

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi
